export interface Item {
  name: string;
  brand: string;
  originalPrice: number;
  discountRate: number;
  reviewCount: number;
  likeCount: number;
  category: string;
  image: string;
}

export const itemArr: Item[] = [
  {
    name: "한송이 화병",
    brand: "수북도예",
    originalPrice: 51000,
    discountRate: 50,
    reviewCount: 123,
    likeCount: 112,
    category: "기타",
    image: "/assets/workitem/한송이 화병.jpg",
  },
  {
    name: "사계 수저받침",
    brand: "플로머드",
    originalPrice: 9100,
    discountRate: 50,
    reviewCount: 43,
    likeCount: 112,
    category: "식기",
    image: "/assets/workitem/사계 수저받침.jpg",
  },
  {
    name: "감꽃접시",
    brand: "플로머드",
    originalPrice: 19500,
    discountRate: 50,
    reviewCount: 43,
    likeCount: 112,
    category: "식기",
    image: "/assets/workitem/감꽃접시.jpg",
  },
  {
    name: "도자기 핸드드리퍼",
    brand: "플로머드",
    originalPrice: 9100,
    discountRate: 50,
    reviewCount: 43,
    likeCount: 112,
    category: "식기",
    image: "/assets/workitem/도자기 핸드드리퍼.jpg",
  },
  {
    name: "풍요항아리",
    brand: "수북도예",
    originalPrice: 1235000,
    discountRate: 50,
    reviewCount: 43,
    likeCount: 112,
    category: "기타",
    image: "/assets/workitem/풍요 항아리.jpg",
  },
  {
    name: "대나무 다육다이",
    brand: "진아공예",
    originalPrice: 23000,
    discountRate: 50,
    reviewCount: 43,
    likeCount: 112,
    category: "식기",
    image: "/assets/workitem/대나무 다육다이.jpg",
  },
  {
    name: "대살 안마기",
    brand: "진아공예",
    originalPrice: 13000,
    discountRate: 50,
    reviewCount: 43,
    likeCount: 112,
    category: "기타",
    image: "/assets/workitem/대살 안마기.jpg",
  },
  {
    name: "그림선",
    brand: "금원부채공방",
    originalPrice: 130000,
    discountRate: 50,
    reviewCount: 43,
    likeCount: 112,
    category: "기타",
    image: "/assets/workitem/그림선(수제).jpg",
  },
  {
    name: "표정 술잔/찻잔",
    brand: "솜도자기",
    originalPrice: 9100,
    discountRate: 50,
    reviewCount: 43,
    likeCount: 112,
    category: "식기",
    image: "/assets/workitem/표정 술잔,찻잔.jpg",
  },
  {
    name: "옻칠 바루",
    brand: "송명목공예",
    originalPrice: 550000,
    discountRate: 50,
    reviewCount: 43,
    likeCount: 112,
    category: "기타",
    image: "/assets/workitem/옻칠 바루.jpg",
  },
  {
    name: "수저 젓가락 세트",
    brand: "유성공예사",
    originalPrice: 11050,
    discountRate: 50,
    reviewCount: 43,
    likeCount: 112,
    category: "식기",
    image: "/assets/workitem/수저 젓가락 세트.jpg",
  },
  {
    name: "옻칠 수저",
    brand: "송명목공예",
    originalPrice: 25000,
    discountRate: 50,
    reviewCount: 43,
    likeCount: 112,
    category: "식기",
    image: "/assets/workitem/옻칠 수저.jpg",
  },
  {
    name: "금박 옻칠 수저",
    brand: "송명목공예",
    originalPrice: 52000,
    discountRate: 50,
    reviewCount: 43,
    likeCount: 112,
    category: "식기",
    image: "/assets/workitem/금박 옻칠 수저.jpg",
  },
  {
    name: "둥근 티스푼",
    brand: "송명목공예",
    originalPrice: 19500,
    discountRate: 50,
    reviewCount: 43,
    likeCount: 112,
    category: "식기",
    image: "/assets/workitem/둥근 티스푼.jpg",
  },
  {
    name: "주병세트",
    brand: "솜도자기",
    originalPrice: 78000,
    discountRate: 50,
    reviewCount: 43,
    likeCount: 112,
    category: "식기",
    image: "/assets/workitem/주병세트.jpg",
  },
  {
    name: "디저트볼 그릇",
    brand: "솜도자기",
    originalPrice: 15600,
    discountRate: 50,
    reviewCount: 43,
    likeCount: 112,
    category: "식기",
    image: "/assets/workitem/디저트볼 그릇.jpg",
  },
  {
    name: "나눔잔",
    brand: "수북도예",
    originalPrice: 17000,
    discountRate: 50,
    reviewCount: 43,
    likeCount: 112,
    category: "식기",
    image: "/assets/workitem/나눔잔.jpg",
  },
  {
    name: "대나무 손잡이 컵",
    brand: "진아공예",
    originalPrice: 13000,
    discountRate: 50,
    reviewCount: 43,
    likeCount: 112,
    category: "식기",
    image: "/assets/workitem/대나무 손잡이 컵.jpg",
  },
  {
    name: "치즈도마 (소/대)",
    brand: "꿈꾸는대나무공예",
    originalPrice: 19500,
    discountRate: 50,
    reviewCount: 43,
    likeCount: 112,
    category: "식기",
    image: "/assets/workitem/치즈도마.jpg",
  },
  {
    name: "작_품2",
    brand: "작품",
    originalPrice: 195000,
    discountRate: 50,
    reviewCount: 43,
    likeCount: 112,
    category: "필기도구",
    image: "/assets/workitem/작품2.jpg",
  },
  {
    name: "팬더 마그네틱",
    brand: "솜도자기",
    originalPrice: 6000,
    discountRate: 50,
    reviewCount: 43,
    likeCount: 112,
    category: "기타",
    image: "/assets/workitem/팬더 마그네틱.jpg",
  },
  {
    name: "사선 스카프",
    brand: "자연나드리",
    originalPrice: 62000,
    discountRate: 50,
    reviewCount: 43,
    likeCount: 112,
    category: "옷",
    image: "/assets/workitem/사선 스카프.jpg",
  },
  {
    name: "대나무 손수건",
    brand: "자연나드리",
    originalPrice: 19500,
    discountRate: 50,
    reviewCount: 43,
    likeCount: 112,
    category: "옷",
    image: "/assets/workitem/대나무 손수건.jpg",
  },
  {
    name: "효자봉",
    brand: "작품",
    originalPrice: 195000,
    discountRate: 50,
    reviewCount: 43,
    likeCount: 112,
    category: "기타",
    image: "/assets/workitem/효자봉.jpg",
  },
  {
    name: "대나무 효자손",
    brand: "유성공예사",
    originalPrice: 8000,
    discountRate: 50,
    reviewCount: 43,
    likeCount: 112,
    category: "기타",
    image: "/assets/workitem/대나무 효자손.jpg",
  },
  {
    name: "대살 안마기",
    brand: "진아공예",
    originalPrice: 13000,
    discountRate: 50,
    reviewCount: 43,
    likeCount: 112,
    category: "기타",
    image: "/assets/workitem/대살 안마기.jpg",
  },
  {
    name: "원찻상",
    brand: "유성공예사",
    originalPrice: 150000,
    discountRate: 50,
    reviewCount: 43,
    likeCount: 112,
    category: "가구",
    image: "/assets/workitem/원찻상.jpg",
  },

  {
    name: "12각 찻상",
    brand: "유성공예사",
    originalPrice: 520000,
    discountRate: 50,
    reviewCount: 43,
    likeCount: 112,
    category: "가구",
    image: "/assets/workitem/12각 찻상.jpg",
  },
  {
    name: "라운드도마 (대/특대)",
    brand: "꿈꾸는대나무공예",
    originalPrice: 150000,
    discountRate: 50,
    reviewCount: 43,
    likeCount: 112,
    category: "식기",
    image: "/assets/workitem/라운드도마 (대,특대).jpg",
  },

  {
    name: "오십견 (소/대)",
    brand: "나손길 장인",
    originalPrice: 19500,
    discountRate: 50,
    reviewCount: 43,
    likeCount: 112,
    category: "기타",
    image: "/assets/workitem/오십견.jpg",
  },
  {
    name: "작_품1",
    brand: "작품",
    originalPrice: 65000,
    discountRate: 50,
    reviewCount: 43,
    likeCount: 112,
    category: "필기용품",
    image: "/assets/workitem/작품1.jpg",
  },
  {
    name: "은꽃공 목걸이",
    brand: "해드리움",
    originalPrice: 350000,
    discountRate: 50,
    reviewCount: 43,
    likeCount: 112,
    category: "기타",
    image: "/assets/workitem/꽃공 목걸이.jpg",
  },
  {
    name: "은나비 팔찌",
    brand: "해드리움",
    originalPrice: 260000,
    discountRate: 50,
    reviewCount: 43,
    likeCount: 112,
    category: "악세서리",
    image: "/assets/workitem/은나비 팔찌.jpg",
  },
  {
    name: "대나무 브로치",
    brand: "예담공예",
    originalPrice: 50000,
    discountRate: 50,
    reviewCount: 43,
    likeCount: 112,
    category: "악세서리",
    image: "/assets/workitem/대나무 브로치.jpg",
  },
  {
    name: "민합죽선",
    brand: "금원부채공방",
    originalPrice: 30000,
    discountRate: 50,
    reviewCount: 43,
    likeCount: 112,
    category: "기타",
    image: "/assets/workitem/민합죽선.jpg",
  },
  {
    name: "육각화병",
    brand: "플로머드",
    originalPrice: 100000,
    discountRate: 50,
    reviewCount: 43,
    likeCount: 112,
    category: "가구",
    image: "/assets/workitem/육각화병.jpg",
  },
];
